// Generated by gencpp from file hello_ros/turtle.msg
// DO NOT EDIT!


#ifndef HELLO_ROS_MESSAGE_TURTLE_H
#define HELLO_ROS_MESSAGE_TURTLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_ros
{
template <class ContainerAllocator>
struct turtle_
{
  typedef turtle_<ContainerAllocator> Type;

  turtle_()
    : name()
    , speed(0.0)  {
    }
  turtle_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::hello_ros::turtle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_ros::turtle_<ContainerAllocator> const> ConstPtr;

}; // struct turtle_

typedef ::hello_ros::turtle_<std::allocator<void> > turtle;

typedef boost::shared_ptr< ::hello_ros::turtle > turtlePtr;
typedef boost::shared_ptr< ::hello_ros::turtle const> turtleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_ros::turtle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_ros::turtle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hello_ros::turtle_<ContainerAllocator1> & lhs, const ::hello_ros::turtle_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hello_ros::turtle_<ContainerAllocator1> & lhs, const ::hello_ros::turtle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hello_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::turtle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_ros::turtle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_ros::turtle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_ros::turtle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::turtle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_ros::turtle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_ros::turtle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "731354329381c2f16be8e48fe990ad74";
  }

  static const char* value(const ::hello_ros::turtle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x731354329381c2f1ULL;
  static const uint64_t static_value2 = 0x6be8e48fe990ad74ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_ros::turtle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_ros/turtle";
  }

  static const char* value(const ::hello_ros::turtle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_ros::turtle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float32 speed\n"
;
  }

  static const char* value(const ::hello_ros::turtle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_ros::turtle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_ros::turtle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_ros::turtle_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_ROS_MESSAGE_TURTLE_H
